### ISSUE TITLE
Shortcut ALT + e run a11ychecker

### ISSUE THREAD

**Issue by GitDaimos** [cksource/ckeditor-plugin-a11ychecker#241] opened 2017-03-16 16:16 UTC
I just downloaded a11ychecker. Alt + e starts validation. Its impossible to write anything in polish language because ALT + e its shortcut for polish letter "ę"

**Comment by mlewand** [comment] 2017-03-16 16:18
Duplicate of  #230 - you'll find a solution there. Let us know if it's working fine for you.

**Closed by mlewand** 2017-03-16 16:18 UTC

**Comment by GitDaimos** [comment] 2017-03-16 18:06
Replace with D will help for sure, thank you 👍 . But what with other languages? D is neutral for all?

**Comment by mlewand** [comment] 2017-03-16 23:56
@GitDaimos TBH I can't tell  with 100% confidence... it would need some deeper research. If you'd be willing to take a try, I'd be happy to hear the conclusion.
